name: Build

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Show Custom Message
        if: always()
        run: |
          echo "Quality Gate Result: ${{ steps.qualitygate.outcome }}"

          if [ "${{ steps.qualitygate.outcome }}" != "success" ]; then
            echo "::error title=SonarQube Failed::❌ Quality Gate Failed! Fix issues before merging."
            exit 1
          else
            echo "::notice title=SonarQube Passed::✅ Code quality is good."
          fi